### ISSUE TITLE
write after end

### ISSUE THREAD

**Issue by LoganDark** [unifiedjs/unified#36]
### Subject of the issue

Trying to install `remark` causes an error thrown by `npm`.

### Environment

macOS 10.14 Mojave, remark (latest), node v10.1.0 (npm 6.0.1)

### Steps to reproduce

`npm i remark`

### Expected behavior

Do I have to explain this?

### Actual behavior

```
oganDark@base ~/nitrogen> npm i --save remark remark-html
events.js:167░░░░░░⸩ ⠦ extract:remark-stringify: sill extract x-is-string@0.1.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.entry.on (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:167░░░░░░⸩ ⠏ extract:property-information: sill extract x-is-string@0.1.0
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.entry.on (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
events.js:167░░░░░░⸩ ⠏ extract:kebab-case: timing audit body Completed in 7ms
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:243:12)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    at PassThrough.Writable.end (_stream_writable.js:582:10)
    at ReadEntry.entry.on (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at ReadEntry.emit (events.js:187:15)
    at ReadEntry.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:182:13)
    at Unzip.emit (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
Emitted 'error' event at:
    at writeAfterEnd (_stream_writable.js:245:10)
    at PassThrough.Writable.write (_stream_writable.js:292:5)
    [... lines matching original stack trace ...]
    at Unzip.write (/Users/LoganDark/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
npm ERR! cancel after 1 retries!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/LoganDark/.npm/_logs/2018-06-07T00_56_49_797Z-debug.log
⏎
```

###### p.s. you spelled "behavior" wrong in the template. /s :^)

**Comment by wooorm** [comment]
This seems to be an npm error! I’m guessing removing `node_modules` and installing again would work. Let me know if not!

Also: `behaviour` is British english :p

**Comment by LoganDark** [comment]
~~British english isn't english!~~

I've already moved to showdown, but thanks for your response!

**Comment by wooorm** [comment]
Aww, a pity! Good luck anyway @LoganDark!
